/**
 ******************************************************************************
 * @file    main_example.c
 * @brief   Example application for the ICM-20948 DMA/I2C driver.
 *
 * This file contains ONLY the application code that belongs inside the
 * "USER CODE" sections of a CubeMX-generated main.c (STM32F4, HAL).
 * Peripheral init (clock, GPIO, DMA, I2C1, USART2, ...) is generated by CubeMX
 * and is not repeated here.
 *
 * Each block is labelled with the USER CODE section it goes into.
 *
 * What the example does:
 *   1. Initialises the IMU and calibrates gyro (still) and magnetometer (moving).
 *   2. Polls the driver every ICM_SAMPLE_PERIOD_MS with a non-blocking DMA read.
 *   3. Converts each finished read to physical units.
 *   4. Estimates roll/pitch with a complementary filter.
 *   5. Optionally streams samples as CSV over UART.
 *
 * CSV line format (when ICM_UART_STREAM_ENABLE is defined):
 *   tick_ms,sample_count,ax_g,ay_g,az_g,gx_dps,gy_dps,gz_dps
 ******************************************************************************
 */

/* ========================================================================== */
/* USER CODE BEGIN Includes                                                    */
/* ========================================================================== */
#include "ICM_20948_DMA_I2C.h"
#include <math.h>
#include <stdio.h>
/* USER CODE END Includes */


/* ========================================================================== */
/* USER CODE BEGIN PD                                                          */
/* ========================================================================== */

/** Polling period for starting a new burst read [ms].
 *  The sensor output rate is ~51 Hz (~20 ms), so polling every 4 ms makes sure
 *  a new sample is picked up quickly. Side effect: the same sample may be read
 *  more than once, so g_sample_count counts reads, not unique samples. */
#define ICM_SAMPLE_PERIOD_MS        (4U)

/** Complementary filter weight of the gyro path (0..1). Higher = trust gyro more. */
#define ICM_COMPLEMENTARY_ALPHA     (0.98F)

/** Nominal sample period used when the measured dt is not usable [s]
 *  (first sample, or a long pause such as a debugger halt). */
#define ICM_NOMINAL_DT_S            (0.02F)

/** Largest dt accepted from the tick counter [s]. */
#define ICM_MAX_DT_S                (0.5F)

/** Number of samples used for calibration (see driver for timing). */
#define ICM_GYRO_CAL_SAMPLES        (200U)   /* ~4 s, keep the IMU still and flat  */
#define ICM_MAG_CAL_SAMPLES         (500U)   /* ~5 s, rotate through all directions */

/** Enable CSV streaming over UART (needs huart2, or change the handle below). */
#define ICM_UART_STREAM_ENABLE
/* USER CODE END PD */


/* ========================================================================== */
/* USER CODE BEGIN PV                                                          */
/* ========================================================================== */

static ICM_Handle_t icm_handle;

static const ICM_HW_t icm_hw =
{
    .hi2c        = &hi2c1,
    /* AD0 -> GND: 0x68, AD0 -> 3V3: 0x69. HAL expects the 8-bit (shifted) address. */
    .i2c_address = (uint16_t)(0x68U << 1U)
};

/* Flat globals so STM32CubeIDE Live Expressions / SWV Data Trace can select
 * them directly (members nested inside a struct are harder to resolve). */
volatile float    g_accel_x_g, g_accel_y_g, g_accel_z_g;      /* [g]    */
volatile float    g_gyro_x_dps, g_gyro_y_dps, g_gyro_z_dps;   /* [deg/s] */
volatile float    g_mag_x_ut, g_mag_y_ut, g_mag_z_ut;         /* [uT]   */
volatile float    g_temp_c;                                   /* [degC] */
volatile float    g_roll_deg;                                 /* [deg]  */
volatile float    g_pitch_deg;                                /* [deg]  */
volatile uint32_t g_icm_fault_flags;                          /* ICM_Fault_t bitmask */
volatile uint32_t g_sample_count;                             /* number of processed reads */
volatile bool     g_mag_available;

static uint32_t s_last_read_start_tick;   /* last time a burst read was started */
static uint32_t s_last_filter_tick;       /* last time the attitude filter ran  */

#if defined(ICM_UART_STREAM_ENABLE)
extern UART_HandleTypeDef huart2;
#endif
/* USER CODE END PV */


/* ========================================================================== */
/* USER CODE BEGIN PFP                                                         */
/* ========================================================================== */
static void App_ImuInit(void);
static void App_ImuTask(void);
static void Imu_PublishData(void);
static void Attitude_UpdateComplementary(void);
#if defined(ICM_UART_STREAM_ENABLE)
static void Imu_StreamCsv(void);
#endif
/* USER CODE END PFP */


/* ========================================================================== */
/* USER CODE BEGIN 2   (inside main(), after all MX_..._Init() calls)          */
/* ========================================================================== */
/*
 *     App_ImuInit();
 */
/* USER CODE END 2 */


/* ========================================================================== */
/* USER CODE BEGIN WHILE   (inside while (1))                                  */
/* ========================================================================== */
/*
 *     App_ImuTask();
 */
/* USER CODE END WHILE */


/* ========================================================================== */
/* USER CODE BEGIN 4   (after main(), before the HAL callbacks)                */
/* ========================================================================== */

/**
 * @brief Initialise the IMU and run both calibrations.
 * @note  Blocking: takes roughly 9-10 s in total because of the calibrations.
 *        The gyro must be still; the magnetometer must be rotated in all directions.
 */
static void App_ImuInit(void)
{
    if (ICM_Init(&icm_handle, &icm_hw) != HAL_OK)
    {
        Error_Handler();
    }

    ICM_CalibrateGyro(&icm_handle, ICM_GYRO_CAL_SAMPLES);

    if (icm_handle.status.mag_available)
    {
        ICM_CalibrateMag(&icm_handle, ICM_MAG_CAL_SAMPLES);
    }

    s_last_read_start_tick = HAL_GetTick();
    s_last_filter_tick     = s_last_read_start_tick;
}

/**
 * @brief One iteration of the IMU task. Call it every pass of the main loop.
 *
 * Order matters:
 *   1. supervise the running DMA read (timeout),
 *   2. recover from errors,
 *   3. consume a finished read,
 *   4. start the next read when the polling period has elapsed.
 */
static void App_ImuTask(void)
{
    ICM_CheckTimeout(&icm_handle);

    if (icm_handle.status.state == ICM_STATE_ERROR)
    {
        ICM_ErrorRecovery(&icm_handle);
    }

    if (icm_handle.status.state == ICM_STATE_DATA_READY)
    {
        ICM_ProcessRaw(&icm_handle);
        Imu_PublishData();
        Attitude_UpdateComplementary();
#if defined(ICM_UART_STREAM_ENABLE)
        Imu_StreamCsv();
#endif
    }

    if ((HAL_GetTick() - s_last_read_start_tick) >= ICM_SAMPLE_PERIOD_MS)
    {
        s_last_read_start_tick = HAL_GetTick();
        (void)ICM_StartBurstRead(&icm_handle);   /* HAL_BUSY if a read is running */
    }
}

/** @brief Copy driver output into the flat debug globals. */
static void Imu_PublishData(void)
{
    g_accel_x_g  = icm_handle.data.accel_g[0];
    g_accel_y_g  = icm_handle.data.accel_g[1];
    g_accel_z_g  = icm_handle.data.accel_g[2];

    g_gyro_x_dps = icm_handle.data.gyro_dps[0];
    g_gyro_y_dps = icm_handle.data.gyro_dps[1];
    g_gyro_z_dps = icm_handle.data.gyro_dps[2];

    g_mag_x_ut   = icm_handle.data.mag_ut[0];
    g_mag_y_ut   = icm_handle.data.mag_ut[1];
    g_mag_z_ut   = icm_handle.data.mag_ut[2];

    g_temp_c          = icm_handle.data.temp_c;
    g_icm_fault_flags = icm_handle.status.fault_flags;
    g_mag_available   = icm_handle.status.mag_available;

    g_sample_count++;
}

/**
 * @brief Roll/pitch estimate: gyro integration blended with accelerometer angles.
 *
 *   angle = alpha * (angle + gyro * dt) + (1 - alpha) * accel_angle
 *
 * Roll and pitch only; there is no yaw (that would need the magnetometer with
 * proper axis alignment and tilt compensation).
 */
static void Attitude_UpdateComplementary(void)
{
    const float rad_to_deg = 180.0F / (float)M_PI;

    /* Angles implied by the gravity vector. */
    const float accel_roll_deg  = atan2f(g_accel_y_g, g_accel_z_g) * rad_to_deg;
    const float accel_pitch_deg = atan2f(-g_accel_x_g,
                                         sqrtf((g_accel_y_g * g_accel_y_g) +
                                               (g_accel_z_g * g_accel_z_g))) * rad_to_deg;

    /* Elapsed time since the previous filter update. */
    const uint32_t now_tick = HAL_GetTick();
    float dt_s = (float)(now_tick - s_last_filter_tick) / 1000.0F;
    s_last_filter_tick = now_tick;

    if ((dt_s <= 0.0F) || (dt_s > ICM_MAX_DT_S))
    {
        /* First sample or an abnormal gap (e.g. long debugger halt):
         * fall back to the nominal period to avoid a jump. */
        dt_s = ICM_NOMINAL_DT_S;
    }

    /* Predict with the gyro, then correct with the accelerometer. */
    const float gyro_roll_pred  = g_roll_deg  + (g_gyro_x_dps * dt_s);
    const float gyro_pitch_pred = g_pitch_deg + (g_gyro_y_dps * dt_s);

    g_roll_deg  = (ICM_COMPLEMENTARY_ALPHA * gyro_roll_pred)
                + ((1.0F - ICM_COMPLEMENTARY_ALPHA) * accel_roll_deg);
    g_pitch_deg = (ICM_COMPLEMENTARY_ALPHA * gyro_pitch_pred)
                + ((1.0F - ICM_COMPLEMENTARY_ALPHA) * accel_pitch_deg);
}

#if defined(ICM_UART_STREAM_ENABLE)
/** @brief Send one CSV line (accel + gyro) over USART2. Blocking, 10 ms timeout. */
static void Imu_StreamCsv(void)
{
    char line[96];

    const int len = snprintf(line, sizeof(line),
                             "%lu,%lu,%.4f,%.4f,%.4f,%.3f,%.3f,%.3f\r\n",
                             (unsigned long)HAL_GetTick(),
                             (unsigned long)g_sample_count,
                             (double)g_accel_x_g, (double)g_accel_y_g, (double)g_accel_z_g,
                             (double)g_gyro_x_dps, (double)g_gyro_y_dps, (double)g_gyro_z_dps);

    if ((len > 0) && ((size_t)len < sizeof(line)))
    {
        (void)HAL_UART_Transmit(&huart2, (uint8_t *)line, (uint16_t)len, 10U);
    }
}
#endif

/* ---- HAL callbacks: forward I2C DMA events to the driver (ISR context) ---- */

void HAL_I2C_MemRxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    if (hi2c->Instance == I2C1)
    {
        ICM_DMA_Callback(&icm_handle);
    }
}

void HAL_I2C_ErrorCallback(I2C_HandleTypeDef *hi2c)
{
    if (hi2c->Instance == I2C1)
    {
        ICM_DMA_ErrorCallback(&icm_handle);
    }
}
/* USER CODE END 4 */